services:
  mysql-database:
    image: mysql:8.0
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lamp-stack-group-15
      MYSQL_USER: group15
      MYSQL_PASSWORD: password
    volumes:
      - ./database/migration:/docker-entrypoint-initdb.d:ro
      # - persistent-data:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./frontend:/var/www/html
      - ./backend:/var/www/backend
      - ./apache-config/backend-api.conf:/etc/apache2/conf-enabled/backend-api.conf:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_DSN: "mysql:host=mysql-database;dbname=lamp-stack-group-15;charset=utf8mb4"
      DB_USER: "group15"
      DB_PASS: "password"
    depends_on:
      - mysql-database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql-database
      - PMA_PORT=3306
    depends_on:
      - mysql-database

